services:
  ia_watcher:
    hostname:         ia_watcher.innovanon.com
    build:
      context:        .
      tags:
        - ia_watcher:latest
    restart:          no
    logging:
      driver:         syslog   
