services:
  ia_watcher:
    hostname:         ia_watcher.innovanon.com
    build:
      context:        .
      tags:
        - innovanon/ia_watcher:latest
        -           ia_watcher:latest
        - innovanon/ia_watcher
        -           ia_watcher
    restart:          no
    logging:
      driver:         syslog   
